# Generated by Django 4.0.2 on 2022-05-11 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'allergen',
            },
        ),
        migrations.CreateModel(
            name='DrinkCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'drinkcategories',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_new', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startbucks.drinkcategories')),
            ],
            options={
                'db_table': 'drinks',
            },
        ),
        migrations.CreateModel(
            name='DrinkNutritions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('sugar', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('sodium', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('fat', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('caffeine', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('drink', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='startbucks.drinks')),
            ],
            options={
                'db_table': 'drinknutritions',
            },
        ),
        migrations.CreateModel(
            name='DrinkImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=3000)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startbucks.drinks')),
            ],
            options={
                'db_table': 'drinkimages',
            },
        ),
        migrations.AddField(
            model_name='drinkcategories',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startbucks.menu'),
        ),
        migrations.CreateModel(
            name='DrinkAllergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startbucks.allergen')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startbucks.drinks')),
            ],
            options={
                'db_table': 'drinkallergies',
            },
        ),
        migrations.AddField(
            model_name='allergen',
            name='drink',
            field=models.ManyToManyField(through='startbucks.DrinkAllergies', to='startbucks.Drinks'),
        ),
    ]
