# Generated by Django 4.0.2 on 2022-05-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startbucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkallergies',
            name='extraprice',
            field=models.IntegerField(default=0),
        ),
    ]
