# Generated by Django 4.0.2 on 2022-05-10 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table='Signup',
        ),
    ]
