# Generated by Django 4.0.2 on 2022-05-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_alter_signup_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='phonenumber',
            field=models.CharField(max_length=45),
        ),
    ]
