# Generated by Django 4.0.2 on 2022-05-11 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_alter_signup_phonenumber'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table='signup',
        ),
    ]
