# Generated by Django 4.0.2 on 2022-05-12 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_alter_signup_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
