# Generated by Django 4.0.2 on 2022-05-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0005_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('phonenumber', models.CharField(max_length=45)),
                ('personal', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
