# Generated by Django 4.0.4 on 2022-05-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('phonenumber', models.CharField(max_length=45)),
                ('personal', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
